package cmd

var backendCommands = []commandType{
	{command: "server", typ: "mkdir"},
	{command: "/server", typ: "cd"},
	{command: "npm init -y", typ: "exec"},
	{command: "npm install express", typ: "exec"},
	{command: "npm install dotenv", typ: "exec"},
	{command: "npm install cors", typ: "exec"},
	{command: "npm install jsonwebtoken", typ: "exec"},
	{command: "npm install mongoose", typ: "exec"},
	{command: "models", typ: "mkdir"},
	{command: "controllers", typ: "mkdir"},
	{command: "routes", typ: "mkdir"},
	{command: "config", typ: "mkdir"},
	{command: ".env", typ: "write", content: ServerEnv},
	{command: "/server/config", typ: "cd"},
	{command: "database.js", typ: "write", content: Database},
	{command: "/server", typ: "cd"},
	{command: ".gitignore", typ: "write", content: GitIgn},
	{command: "index.js", typ: "write", content: ServerData},
}

func reactNativeCommands(projName string) []commandType {
	if projName == "" {
		projName = "MyProject"
	}
	return []commandType{
		{command: "npm i -g @react-native-community/cli", typ: "exec"},
		{command: "npx @react-native-community/cli init " + projName, typ: "exec"},
		{command: "/" + projName, typ: "cd"},
		{command: "npm install @types/react-native", typ: "exec"},
		{command: "tsconfig.json", typ: "write", content: tsConfig},
		{command: "eslint.config.js", typ: "write", content: esConfig},
		{command: "npm install nativewind", typ: "exec"},
		{command: "npm install --save-dev tailwindcss@3.3.2", typ: "exec"},
		{command: "tailwind.config.js", typ: "write", content: TWConfig},
		{command: ".eslintrc.js", typ: "write", content: Eslint},
		{command: "babel.config.js", typ: "write", content: TWBabel},
		{command: "nativewind-env.d.ts", typ: "write", content: Nenvdts},
		{command: "npm install @react-navigation/bottom-tabs", typ: "exec"},
		{command: "npm install react-native-screens", typ: "exec"},
		{command: "npm install @react-navigation/native-stack", typ: "exec"},
		{command: "npm install @react-navigation/native", typ: "exec"},
		{command: "npm install @react-navigation/drawer", typ: "exec"},
		{command: "npm install react-native-safe-area-context", typ: "exec"},
		{command: "npm install @react-native-async-storage/async-storage", typ: "exec"},
		{command: "npm install dotenv", typ: "exec"},
		{command: "npm install react-native-dotenv", typ: "exec"},
		{command: "npm install react-native-gesture-handler", typ: "exec"},
		{command: "npm install react-native-reanimated", typ: "exec"},
		{command: "babel.config.js", typ: "write", content: BabelFull},
		{command: "env.d.ts", typ: "write", content: envdts},
		{command: "npm install react-native-safe-area-context", typ: "exec"},
		{command: "npm install react-native-vector-icons", typ: "exec"},
		{command: "/" + projName + "/android/app", typ: "cd"},
		{command: "build.gradle", typ: "write", content: buildGradel},
		{command: "/" + projName, typ: "cd"},
		{command: "npm install react-redux", typ: "exec"},
		{command: "npm install redux-persist", typ: "exec"},
		{command: "npm install @reduxjs/toolkit", typ: "exec"},
		{command: "src", typ: "mkdir"},
		{command: "/" + projName + "/src", typ: "cd"},
		{command: "index.tsx", typ: "write", content: " "},
		{command: "redux", typ: "mkdir"},
		{command: "/" + projName + "/src/redux", typ: "cd"},
		{command: "store.js", typ: "write", content: store},
		{command: "root_reducers.js", typ: "write", content: rootRed},
		{command: "slices", typ: "mkdir"},
		{command: "/" + projName + "/src/redux/slices", typ: "cd"},
		{command: "temp.js", typ: "write", content: tempSlice},

		{command: "/" + projName, typ: "cd"},
	}
}
